# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190522_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
