# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190507_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
