# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-08 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_timstamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
